#!/usr/bin/env python3
"""Gate coach-facing COUG reports on reconciliation issue signoffs.

The check reads the season triage CSV generated by
``build_reconciliation_triage.py`` and matches actionable discrepancies to the
tracked analyst signoff register. A missing or incomplete signoff blocks
publication; documented source gaps and known gaps pass with warnings.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REPORT_ROOT = REPO_ROOT / "pipeline" / "outputs" / "reports" / "score_reconciliation"
DEFAULT_SIGNOFFS = REPO_ROOT / "pipeline" / "config" / "reconciliation_signoffs.csv"

ISSUE_TYPES = {
    "needs_source_review",
    "candidate_below_legacy",
    "legacy_only_player",
}
PASS_DISPOSITIONS = {"cleared"}
WARNING_DISPOSITIONS = {"source_missing", "known_gap"}
BLOCK_DISPOSITIONS = {"under_review"}
ALLOWED_DISPOSITIONS = PASS_DISPOSITIONS | WARNING_DISPOSITIONS | BLOCK_DISPOSITIONS
SIGNOFF_COLUMNS = [
    "season",
    "slug",
    "player_key",
    "issue_type",
    "disposition",
    "note",
    "reviewed_by",
    "reviewed_date",
]


@dataclass(frozen=True)
class Issue:
    season: str
    slug: str
    player_key: str
    issue_type: str

    @property
    def key(self) -> tuple[str, str, str, str]:
        return (self.season, self.slug, self.player_key, self.issue_type)


def clean(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).strip()


def as_number(value: object) -> float:
    number = pd.to_numeric(value, errors="coerce")
    return 0.0 if pd.isna(number) else float(number)


def load_actionable_issues(path: Path, season: str) -> list[Issue]:
    if not path.exists():
        raise FileNotFoundError(
            f"Triage CSV not found: {path}\n"
            "Run pipeline/analytics/build_reconciliation_triage.py first."
        )

    triage = pd.read_csv(path)
    required = {"slug", "triage_status", "triage_player"}
    missing = required - set(triage.columns)
    if missing:
        raise ValueError(f"Triage CSV is missing required columns: {', '.join(sorted(missing))}")

    issues: list[Issue] = []
    for _, row in triage.iterrows():
        issue_type = clean(row["triage_status"])
        if issue_type not in ISSUE_TYPES:
            continue
        # Legacy-only zero rows are roster/alias comparison artifacts, not
        # scoring discrepancies. Positive legacy PEAK rows require review.
        if issue_type == "legacy_only_player" and as_number(row.get("legacy_peak")) <= 0:
            continue
        issues.append(
            Issue(
                season=season,
                slug=clean(row["slug"]),
                player_key=clean(row["triage_player"]),
                issue_type=issue_type,
            )
        )
    return sorted(set(issues), key=lambda item: item.key)


def load_signoffs(path: Path) -> tuple[dict[tuple[str, str, str, str], dict[str, str]], list[str]]:
    if not path.exists():
        raise FileNotFoundError(f"Signoff register not found: {path}")

    errors: list[str] = []
    signoffs: dict[tuple[str, str, str, str], dict[str, str]] = {}
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = set(SIGNOFF_COLUMNS) - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Signoff register is missing columns: {', '.join(sorted(missing))}")

        for line_number, raw in enumerate(reader, start=2):
            row = {column: clean(raw.get(column)) for column in SIGNOFF_COLUMNS}
            key = (row["season"], row["slug"], row["player_key"], row["issue_type"])
            if key in signoffs:
                errors.append(f"line {line_number}: duplicate signoff for {' / '.join(key)}")
                continue
            if row["issue_type"] not in ISSUE_TYPES:
                errors.append(f"line {line_number}: unknown issue_type '{row['issue_type']}'")
            if row["disposition"] not in ALLOWED_DISPOSITIONS:
                errors.append(f"line {line_number}: unknown disposition '{row['disposition']}'")
            if not row["note"] or not row["reviewed_by"] or not row["reviewed_date"]:
                errors.append(f"line {line_number}: note, reviewed_by, and reviewed_date are required")
            signoffs[key] = row
    return signoffs, errors


def markdown_report(
    season: str,
    issues: list[Issue],
    warnings: list[tuple[Issue, dict[str, str]]],
    blocks: list[tuple[Issue, str]],
    stale_count: int,
) -> str:
    status = "BLOCKED" if blocks else ("PASSED WITH WARNINGS" if warnings else "PASSED")
    lines = [
        f"# COUG Reconciliation Preflight — {season}",
        "",
        f"**Status: {status}**",
        "",
        f"- Actionable issues: {len(issues)}",
        f"- Documented warnings: {len(warnings)}",
        f"- Blocking issues: {len(blocks)}",
        f"- Stale signoffs not present in current triage: {stale_count}",
        "",
    ]
    if blocks:
        lines.extend(["## Blocks", ""])
        for issue, reason in blocks:
            lines.append(
                f"- `{issue.slug}` — {issue.player_key} — `{issue.issue_type}`: {reason}"
            )
        lines.append("")
    if warnings:
        lines.extend(["## Documented Warnings", ""])
        for issue, signoff in warnings:
            lines.append(
                f"- `{issue.slug}` — {issue.player_key} — "
                f"`{signoff['disposition']}`: {signoff['note']}"
            )
        lines.append("")
    lines.extend([
        "## Disposition Reference",
        "",
        "- `cleared`: investigated and resolved; passes silently.",
        "- `source_missing`: documented unavailable evidence; passes with warning.",
        "- `known_gap`: understood future scoring gap; passes with warning.",
        "- `under_review` or no valid signoff: blocks publication.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Check COUG reconciliation issues against analyst signoffs")
    parser.add_argument("--season", default="2025")
    parser.add_argument("--triage", type=Path, help="Override the generated season triage CSV")
    parser.add_argument("--signoffs", type=Path, default=DEFAULT_SIGNOFFS)
    parser.add_argument("--output", type=Path, help="Write a Markdown preflight report")
    args = parser.parse_args()

    season = str(args.season)
    triage_path = args.triage or DEFAULT_REPORT_ROOT / season / f"{season}_reconciliation_triage.csv"

    try:
        issues = load_actionable_issues(triage_path, season)
        signoffs, register_errors = load_signoffs(args.signoffs)
    except (FileNotFoundError, ValueError) as exc:
        print(f"BLOCKED — {exc}")
        return 1

    warnings: list[tuple[Issue, dict[str, str]]] = []
    blocks: list[tuple[Issue, str]] = []
    issue_keys = {issue.key for issue in issues}

    for error in register_errors:
        blocks.append((Issue(season, "signoff-register", "", "configuration"), error))

    for issue in issues:
        signoff = signoffs.get(issue.key)
        if not signoff:
            blocks.append((issue, "no analyst signoff"))
        elif signoff["disposition"] in WARNING_DISPOSITIONS:
            warnings.append((issue, signoff))
        elif signoff["disposition"] in BLOCK_DISPOSITIONS:
            blocks.append((issue, f"disposition is {signoff['disposition']}"))
        elif signoff["disposition"] not in PASS_DISPOSITIONS:
            blocks.append((issue, f"invalid disposition '{signoff['disposition']}'"))

    season_signoff_keys = {key for key in signoffs if key[0] == season}
    stale_count = len(season_signoff_keys - issue_keys)
    report = markdown_report(season, issues, warnings, blocks, stale_count)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
        print(f"Wrote {args.output}")

    if blocks:
        print(f"BLOCKED — {len(issues)} actionable issues, {len(warnings)} warnings, {len(blocks)} blocks")
        for issue, reason in blocks:
            print(f"  {issue.slug} | {issue.player_key} | {issue.issue_type} | {reason}")
        return 1
    if warnings:
        print(f"PASSED WITH WARNINGS — {len(warnings)} documented issues, 0 blocks")
        return 0
    print(f"PASSED — {len(issues)} actionable issues, 0 blocks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
